name: Deploy to AWS with CDK

on:
  push:
    branches:
      - production
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # 環境変数の設定
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Set environment
      id: set_env
      run: |
        if [[ $GITHUB_REF == 'refs/heads/production' ]]; then
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
        fi

    - name: Deploy with CDK
      run: npx cdk deploy --all --require-approval never
      env:
        ENVIRONMENT: ${{ env.ENVIRONMENT }}
